/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "parser_tester.hpp"

using namespace roq;
using namespace roq::btse_futures;

using namespace std::literals;

using value_type = json::Positions;

TEST_CASE("long", "[json_positions]") {
  auto message = R"({)"
                 R"("topic":"positionsV3",)"
                 R"("data":[{)"
                 R"("requestId":0,)"
                 R"("username":"thraneh",)"
                 R"("userCurrency":null,)"
                 R"("marketName":"BTC-PERP-USDT",)"
                 R"("orderType":90,)"
                 R"("orderMode":66,)"
                 R"("status":65,)"
                 R"("originalAmount":0.00001,)"
                 R"("maxPriceHeld":0,)"
                 R"("pegPriceMin":0,)"
                 R"("stealth":1,)"
                 R"("baseCurrency":null,)"
                 R"("quoteCurrency":null,)"
                 R"("quoteCurrencyFiat":false,)"
                 R"("parents":null,)"
                 R"("makerFeesRatio":null,)"
                 R"("takerFeesRatio":[5.5E-4],)"
                 R"("orderID":null,)"
                 R"("vendorName":null,)"
                 R"("botID":null,)"
                 R"("maxStealthDisplayAmount":0,)"
                 R"("tag":null,)"
                 R"("triggerPrice":0,)"
                 R"("closeOrder":false,)"
                 R"("dbBaseBalHeld":0,)"
                 R"("dbQuoteBalHeld":-0.03572612,)"
                 R"("isFuture":true,)"
                 R"("liquidationInProgress":false,)"
                 R"("marginType":91,)"
                 R"("entryPrice":89315.3,)"
                 R"("liquidationPrice":0,)"
                 R"("markedPrice":89315.3,)"
                 R"("marginHeld":0,)"
                 R"("unrealizedProfitLoss":0,)"
                 R"("totalMaintenanceMargin":0.004956999,)"
                 R"("totalContracts":1,)"
                 R"("marginChargedLongOpen":0,)"
                 R"("marginChargedShortOpen":0,)"
                 R"("unchargedMarginLongOpen":0,)"
                 R"("unchargedMarginShortOpen":0,)"
                 R"("isolatedCurrency":null,)"
                 R"("isolatedLeverage":25,)"
                 R"("totalFees":0,)"
                 R"("totalValue":0.893153,)"
                 R"("adlScoreBucket":1,)"
                 R"("adlScorePercentile":0.4068965517,)"
                 R"("orderTypeName":"TYPE_FUTURES_POSITION",)"
                 R"("orderModeName":"MODE_BUY",)"
                 R"("marginTypeName":"FUTURES_MARGIN_CROSS",)"
                 R"("currentLeverage":0.0000893153,)"
                 R"("contractSize":0.00001,)"
                 R"("minimumRequiredMargin":0,)"
                 R"("filledSize":0,)"
                 R"("takeProfitOrder":null,)"
                 R"("stopLossOrder":null,)"
                 R"("positionId":"BTC-PERP-USDT",)"
                 R"("activeWalletName":"CROSS@",)"
                 R"("positionMode":"ONE_WAY",)"
                 R"("positionDirection":"LONG",)"
                 R"("serviceType":0,)"
                 R"("avgFilledPrice":0,)"
                 R"("sellExchangeRate":0,)"
                 R"("future":true,)"
                 R"("settleWithNonUSDAsset":"USDT")"
                 R"(})"
                 R"(])"
                 R"(})";
  auto helper = [](value_type const &obj) {
    CHECK(obj.topic == "positionsV3"sv);
    REQUIRE(std::size(obj.data) == 1);
  };
  ParserTester<value_type>::dispatch(helper, message, 8192, 1);
}

TEST_CASE("flat", "[json_positions]") {
  auto message = R"({)"
                 R"("topic":"positionsV3",)"
                 R"("data":[{)"
                 R"("requestId":0,)"
                 R"("username":"thraneh",)"
                 R"("userCurrency":null,)"
                 R"("marketName":"BTC-PERP-USDT",)"
                 R"("orderType":0,)"
                 R"("orderMode":0,)"
                 R"("status":65,)"
                 R"("originalAmount":0,)"
                 R"("maxPriceHeld":0,)"
                 R"("pegPriceMin":0,)"
                 R"("stealth":0,)"
                 R"("baseCurrency":null,)"
                 R"("quoteCurrency":null,)"
                 R"("quoteCurrencyFiat":false,)"
                 R"("parents":null,)"
                 R"("makerFeesRatio":null,)"
                 R"("takerFeesRatio":null,)"
                 R"("orderID":null,)"
                 R"("vendorName":null,)"
                 R"("botID":null,)"
                 R"("maxStealthDisplayAmount":0,)"
                 R"("tag":null,)"
                 R"("triggerPrice":0,)"
                 R"("closeOrder":false,)"
                 R"("dbBaseBalHeld":0,)"
                 R"("dbQuoteBalHeld":0,)"
                 R"("isFuture":false,)"
                 R"("liquidationInProgress":false,)"
                 R"("marginType":0,)"
                 R"("entryPrice":0,)"
                 R"("liquidationPrice":0,)"
                 R"("markedPrice":0,)"
                 R"("marginHeld":0,)"
                 R"("unrealizedProfitLoss":0,)"
                 R"("totalMaintenanceMargin":0,)"
                 R"("totalContracts":0,)"
                 R"("marginChargedLongOpen":0,)"
                 R"("marginChargedShortOpen":0,)"
                 R"("unchargedMarginLongOpen":0,)"
                 R"("unchargedMarginShortOpen":0,)"
                 R"("isolatedCurrency":null,)"
                 R"("isolatedLeverage":0,)"
                 R"("totalFees":0,)"
                 R"("totalValue":0,)"
                 R"("adlScoreBucket":0,)"
                 R"("adlScorePercentile":0,)"
                 R"("orderTypeName":null,)"
                 R"("orderModeName":null,)"
                 R"("marginTypeName":null,)"
                 R"("currentLeverage":0,)"
                 R"("contractSize":0,)"
                 R"("minimumRequiredMargin":0,)"
                 R"("filledSize":0,)"
                 R"("takeProfitOrder":null,)"
                 R"("stopLossOrder":null,)"
                 R"("positionId":"BTC-PERP-USDT",)"
                 R"("activeWalletName":null,)"
                 R"("positionMode":null,)"
                 R"("positionDirection":null,)"
                 R"("serviceType":0,)"
                 R"("avgFilledPrice":0,)"
                 R"("sellExchangeRate":0,)"
                 R"("future":false,)"
                 R"("settleWithNonUSDAsset":"USD")"
                 R"(})"
                 R"(])"
                 R"(})";
  auto helper = [](value_type const &obj) {
    CHECK(obj.topic == "positionsV3"sv);
    REQUIRE(std::size(obj.data) == 1);
  };
  ParserTester<value_type>::dispatch(helper, message, 8192, 1);
}

TEST_CASE("short", "[json_positions]") {
  auto message = R"({)"
                 R"("topic":"positionsV3",)"
                 R"("data":[{)"
                 R"("requestId":0,)"
                 R"("username":"thraneh",)"
                 R"("userCurrency":null,)"
                 R"("marketName":"BTC-PERP-USDT",)"
                 R"("orderType":90,)"
                 R"("orderMode":83,)"
                 R"("status":65,)"
                 R"("originalAmount":0.00001,)"
                 R"("maxPriceHeld":0,)"
                 R"("pegPriceMin":0,)"
                 R"("stealth":1,)"
                 R"("baseCurrency":null,)"
                 R"("quoteCurrency":null,)"
                 R"("quoteCurrencyFiat":false,)"
                 R"("parents":null,)"
                 R"("makerFeesRatio":null,)"
                 R"("takerFeesRatio":[5.5E-4],)"
                 R"("orderID":null,)"
                 R"("vendorName":null,)"
                 R"("botID":null,)"
                 R"("maxStealthDisplayAmount":0,)"
                 R"("tag":null,)"
                 R"("triggerPrice":0,)"
                 R"("closeOrder":false,)"
                 R"("dbBaseBalHeld":0,)"
                 R"("dbQuoteBalHeld":-0.0358,)"
                 R"("isFuture":true,)"
                 R"("liquidationInProgress":false,)"
                 R"("marginType":91,)"
                 R"("entryPrice":89502.7,)"
                 R"("liquidationPrice":994520017.5427606,)"
                 R"("markedPrice":89500,)"
                 R"("marginHeld":0,)"
                 R"("unrealizedProfitLoss":0.000027,)"
                 R"("totalMaintenanceMargin":0.004980854,)"
                 R"("totalContracts":1,)"
                 R"("marginChargedLongOpen":0,)"
                 R"("marginChargedShortOpen":0,)"
                 R"("unchargedMarginLongOpen":0,)"
                 R"("unchargedMarginShortOpen":0,)"
                 R"("isolatedCurrency":null,)"
                 R"("isolatedLeverage":25,)"
                 R"("totalFees":0,)"
                 R"("totalValue":-0.895,)"
                 R"("adlScoreBucket":1,)"
                 R"("adlScorePercentile":0,)"
                 R"("orderTypeName":"TYPE_FUTURES_POSITION",)"
                 R"("orderModeName":"MODE_SELL",)"
                 R"("marginTypeName":"FUTURES_MARGIN_CROSS",)"
                 R"("currentLeverage":0.0000895,)"
                 R"("contractSize":0.00001,)"
                 R"("minimumRequiredMargin":0,)"
                 R"("filledSize":0,)"
                 R"("takeProfitOrder":null,)"
                 R"("stopLossOrder":null,)"
                 R"("positionId":"BTC-PERP-USDT",)"
                 R"("activeWalletName":"CROSS@",)"
                 R"("positionMode":"ONE_WAY",)"
                 R"("positionDirection":"SHORT",)"
                 R"("serviceType":0,)"
                 R"("avgFilledPrice":0,)"
                 R"("sellExchangeRate":0,)"
                 R"("future":true,)"
                 R"("settleWithNonUSDAsset":"USDT")"
                 R"(})"
                 R"(])"
                 R"(})";
  auto helper = [](value_type const &obj) {
    CHECK(obj.topic == "positionsV3"sv);
    REQUIRE(std::size(obj.data) == 1);
  };
  ParserTester<value_type>::dispatch(helper, message, 8192, 1);
}

// not sure why we got 2 updates...?
TEST_CASE("short_2", "[json_positions]") {
  auto message = R"({)"
                 R"("topic":"positionsV3",)"
                 R"("data":[{)"
                 R"("requestId":0,)"
                 R"("username":"thraneh",)"
                 R"("userCurrency":null,)"
                 R"("marketName":"BTC-PERP-USDT",)"
                 R"("orderType":90,)"
                 R"("orderMode":83,)"
                 R"("status":65,)"
                 R"("originalAmount":0.00001,)"
                 R"("maxPriceHeld":0,)"
                 R"("pegPriceMin":0,)"
                 R"("stealth":1,)"
                 R"("baseCurrency":null,)"
                 R"("quoteCurrency":null,)"
                 R"("quoteCurrencyFiat":false,)"
                 R"("parents":null,)"
                 R"("makerFeesRatio":null,)"
                 R"("takerFeesRatio":[5.5E-4],)"
                 R"("orderID":null,)"
                 R"("vendorName":null,)"
                 R"("botID":null,)"
                 R"("maxStealthDisplayAmount":0,)"
                 R"("tag":null,)"
                 R"("triggerPrice":0,)"
                 R"("closeOrder":false,)"
                 R"("dbBaseBalHeld":0,)"
                 R"("dbQuoteBalHeld":-0.0358,)"
                 R"("isFuture":true,)"
                 R"("liquidationInProgress":false,)"
                 R"("marginType":91,)"
                 R"("entryPrice":89502.7,)"
                 R"("liquidationPrice":994520017.5427606,)"
                 R"("markedPrice":89500,)"
                 R"("marginHeld":0,)"
                 R"("unrealizedProfitLoss":0.000027,)"
                 R"("totalMaintenanceMargin":0.004980854,)"
                 R"("totalContracts":1,)"
                 R"("marginChargedLongOpen":0,)"
                 R"("marginChargedShortOpen":0,)"
                 R"("unchargedMarginLongOpen":0,)"
                 R"("unchargedMarginShortOpen":0,)"
                 R"("isolatedCurrency":null,)"
                 R"("isolatedLeverage":25,)"
                 R"("totalFees":0,)"
                 R"("totalValue":-0.895,)"
                 R"("adlScoreBucket":1,)"
                 R"("adlScorePercentile":0,)"
                 R"("orderTypeName":"TYPE_FUTURES_POSITION",)"
                 R"("orderModeName":"MODE_SELL",)"
                 R"("marginTypeName":"FUTURES_MARGIN_CROSS",)"
                 R"("currentLeverage":0.0000895,)"
                 R"("contractSize":0.00001,)"
                 R"("minimumRequiredMargin":0,)"
                 R"("filledSize":0,)"
                 R"("takeProfitOrder":null,)"
                 R"("stopLossOrder":null,)"
                 R"("positionId":"BTC-PERP-USDT",)"
                 R"("activeWalletName":"CROSS@",)"
                 R"("positionMode":"ONE_WAY",)"
                 R"("positionDirection":"SHORT",)"
                 R"("serviceType":0,)"
                 R"("avgFilledPrice":0,)"
                 R"("sellExchangeRate":0,)"
                 R"("future":true,)"
                 R"("settleWithNonUSDAsset":"USDT")"
                 R"(})"
                 R"(])"
                 R"(})";
  auto helper = [](value_type const &obj) {
    CHECK(obj.topic == "positionsV3"sv);
    REQUIRE(std::size(obj.data) == 1);
  };
  ParserTester<value_type>::dispatch(helper, message, 8192, 1);
}
